### ISSUE TITLE
The Archive

### ISSUE THREAD

**Issue by ddeboer** [alfredapp/updated-third-party-python2-workflows#18]
### Workflow name

The Archive

### Workflow page

https://www.alfredforum.com/topic/15090-alfred-workflow-for-the-archive/

**Comment by vitorgalvao** [comment]
[Added.](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/The%20Archive.alfredworkflow)

**Comment by ddeboer** [comment]
Thanks @vitorgalvao! 

Unfortunately, the updated workflow doesn’t seem to work yet:

```
[17:33:57.363] Logging Started...
[17:33:58.284] The Archive[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228%3E629E7681-4B3B-44F8-931C-617775EE6CFA)] Queuing argument ''
[17:33:58.292] The Archive[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228%3E629E7681-4B3B-44F8-931C-617775EE6CFA)] Script with argv '' finished
[17:33:58.293] ERROR: The Archive[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228%3E629E7681-4B3B-44F8-931C-617775EE6CFA)] Code 127: env: python: No such file or directory
```

I followed https://www.alfredapp.com/help/kb/python-2-monterey/ to install Python 2.

**Comment by vitorgalvao** [comment]
Try it now (same download URL).

**Comment by ddeboer** [comment]
Better now: the workflow no longer complains about finding Python. However, now I’m getting:

```
[08:16:55.272] ERROR: The Archive[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228%3E629E7681-4B3B-44F8-931C-617775EE6CFA)] Code 1: Traceback (most recent call last):
  File "./search_notes.py", line 4, in <module>
    from Alfred import Items, Tools
  File "/Users/david/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228/Alfred.py", line 5, in <module>
    from Plist import Plist
  File "/Users/david/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6BD99F92-B632-49AA-94F0-43FF0655D228/Plist.py", line 5, in <module>
    from Foundation import NSData
ImportError: No module named Foundation
```

And `pip install foundation` fails with:

```
 ImportError: No module named _ctypes
```

**Comment by vitorgalvao** [comment]
That means it requires the Objective-C bridge. There’s a very small subset of Python 2 Workflows who do. At the moment it’s not viable to support those because the required Python packages fail (for me?) to build under Apple Silicon. If you’re on Intel, you may be able to do so (`"${HOME}/.pyenv/versions/2.7.18/bin/python2.7" -m pip install PACKAGE_NAME`) but the build failure makes it impossible for me to support it.

I’m open to workarounds if you have them, but you may need to contact the original developer (should always be the first step) or look for an alternative Workflow (second step).

**Comment by ddeboer** [comment]
I’m on Silicon too and wasn’t able to install the foundation and _ctypes packages either. Anyway, meanwhile the original developer has upgraded the workflow to Python 3 (#29), so we don’t have to worry about this anymore. 😄

Thanks for your effort @vitorgalvao!

**Comment by vitorgalvao** [comment]
It has now been removed from the list. Thank you for the followup.
