### ISSUE TITLE
Error when using I sheet you not

### ISSUE THREAD

**Issue by saramamendes** [alfredapp/updated-third-party-python2-workflows#60]
I have just downloaded the I sheet you not workflow from your list of updated workflows but I get the following error when trying to create the workflow.

[15:10:59.296] I Sheet You Not[Keyword] Processing complete
[15:10:59.298] I Sheet You Not[Keyword] Passing output 'Emails' to Run Script
[15:10:59.371] ERROR: I Sheet You Not[Run Script] Building workflow "Emails" in /Users/saramendes/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not ...
env: python: No such file or directory

I have installed python using Cakebrew but nothing has changed after the install. Do I need to move the install files somewhere else?

Any help would be appreciated.

Thank you

**Comment by vitorgalvao** [comment]
You downloaded the wrong one, get the one from [the alternatives](https://github.com/giovannicoppola/i-sheet-you-not/releases).

**Comment by saramamendes** [comment]
Thank you for the quick reply.

I just downloaded from the link you provided but I get the following error now.

[10:06:04.221] I Sheet You Not[File Filter] Processing complete
[10:06:04.222] I Sheet You Not[File Filter] Passing output '/Users/saramendes/Documents/OBS/Parent Emails 21-22.xlsx' to Arg and Vars
[10:06:04.225] I Sheet You Not[Arg and Vars] Processing complete
[10:06:04.225] I Sheet You Not[Arg and Vars] Passing output '' to Keyword
[10:06:08.153] I Sheet You Not[Keyword] Processing complete
[10:06:08.154] I Sheet You Not[Keyword] Passing output 'Emails' to Run Script
[10:06:08.289] ERROR: I Sheet You Not[Run Script] Building workflow "Emails" in /Users/saramendes/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not ...
Traceback (most recent call last):
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 352, in <module>
    sys.exit(main())
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 338, in main
    o = parse_args()
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 327, in parse_args
    o.target = os.path.join(o.dir, filename(o.name))
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 255, in filename
    return '{}-{}.alfredworkflow'.format(name, version())
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 248, in version
    return run_command([os.path.join(HERE, 'isyn'), '--version'], True).strip()
  File "/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./buildme", line 231, in run_command
    raise CalledProcessError(status, cmd)
subprocess.CalledProcessError: Command '['/Users/saramendes/Documents/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.0D931E3F-5E37-4A4D-896B-DA913E4740C4/./isyn', '--version']' returned non-zero exit status 1.

**Comment by saramamendes** [comment]
I just installed Xcod tools and it worked. Thank you so much!!!
